name: "Pytest Report Annotations"
description: "List failed tests summary and results as annotations."
branding:
  icon: "box"
  color: "green"
inputs:
  path:
    description: "glob to junit xml files"
    required: true
    default: "**/TEST-*.xml"
  numFailures:
    description: "max number of failed tests to include"
    required: true
    default: 10
runs:
  using: "node16"
  main: "index.js"