name: Tests
on: [push]
  # pull_request:
  #   branches: 
  #     - master
  #   types: [opened, synchronize, reopened, ready_for_review]

jobs:
  npm-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
  failure-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test action
        uses: ./
        with:
          path: "**/TEST-Failure.xml"
          debug: true
      - name: Assert failure
        if: success()
        run: |
          echo "::error::failure-tests-notoken should have failed and reported annations on this step. But instead succeeded";
          exit 1;
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test action
        uses: ./
        with:
          name: "error tests no token"
          path: "**/TEST-Error.xml"
          debug: true
      - name: Assert failure
        if: success()
        run: |
          echo "::error::error-tests-notoken should have failed and reported annations on this step. But instead succeeded.";
          exit 1;
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test action
        uses: ./
        with:
          name: "Success tests no token"
          path: "**/TEST-Success.xml"
          debug: true